"""Generate the RightRefer Forward identity. Requires fonttools; see docs/brand."""
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
import json
import re

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'public'
BRAND = PUBLIC / 'brand_assets'
for folder in ('logos', 'symbols', 'icons', 'social', 'downloads'):
    (BRAND / folder).mkdir(parents=True, exist_ok=True)
FONT = ROOT / 'docs/brand/Manrope-SemiBold.ttf'
WORDMARK_FONT = PUBLIC / 'Louize.woff2'
TOKENS = (ROOT / 'src/styles/tokens.css').read_text()


def token(name):
    # First declaration is the light/static identity value.
    match = re.search(r'--color-' + name + r':\s*([\d ]+);', TOKENS)
    return '#' + ''.join(f'{int(channel):02X}' for channel in match.group(1).split())


INK, PAPER, BLUE = token('ink'), token('canvas'), token('primary')
WHITE = token('primary-ink')
TEAL, SKY = token('brand-teal'), token('brand-sky')

# Three independent planes on a 96-unit grid. The gaps are real negative space,
# so the silhouette survives monochrome, small sizes, and arbitrary backgrounds.
PARTS = [
    {'tone': 'primary', 'path': 'M9.4 28.6L25.8 12.2C28.5 9.5 32.1 8 36 8H78.8C82.7 8 84.7 9.5 82.5 11.7L61.5 32.7C59.4 34.8 56.5 36 53.5 36H12.5C6.8 36 5.4 32.6 9.4 28.6Z'},
    {'tone': 'teal', 'path': 'M88 17.5V59.5C88 63.2 86.5 66.7 83.9 69.3L67 86.2C63.3 89.9 60 88.5 60 83.5V47.5C60 42.7 61.9 38.1 65.3 34.7L84.1 15.9C86.3 13.7 88 14.4 88 17.5Z'},
    {'tone': 'sky', 'path': 'M8 69C8 64.5 10.4 60.4 14.3 58.1L43.5 41.3C47.5 39 51 41 51 45.6V61C51 65.5 48.6 69.6 44.7 71.9L15.5 88.7C11.5 91 8 89 8 84.4Z'},
]
COLORS = {'primary': BLUE, 'teal': TEAL, 'sky': SKY}


def outline(text, fontfile, size, x, baseline, tracking=0):
    font = TTFont(fontfile)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = size / font['head'].unitsPerEm
    pen = SVGPathPen(glyphs, ntos=lambda n: format(n, '.3f').rstrip('0').rstrip('.') if n else '0')
    for char in text:
        name = cmap[ord(char)]
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, x, baseline)))
        x += glyphs[name].width * scale + tracking
    return pen.getCommands(), x - tracking


# Louize shares the landing page's display voice. Its finer strokes need a
# larger nominal size than the previous sans-serif wordmark.
WORD, END = outline('RightRefer', WORDMARK_FONT, 58, 76, 47.5, -.4)
WIDTH = round(END + 1, 3)


def mark(color=None):
    return ''.join(f'<path fill="{color or COLORS[p["tone"]]}" d="{p["path"]}"/>' for p in PARTS)


def app_icon(compact=False):
    transform = 'translate(5.5 5) scale(.88)' if compact else 'translate(13 12) scale(.73)'
    return f'<rect width="96" height="96" rx="22" fill="{BLUE}"/><g transform="{transform}">{mark(WHITE)}</g>'


def lockup(word_color=INK, mono=False):
    return f'<g transform="scale(.666667)">{mark(word_color if mono else None)}</g><path fill="{word_color}" d="{WORD}"/>'


def svg(body, w, h, label='RightRefer'):
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{label}">{body}</svg>\n'


for name, color in [('ink', INK), ('white', WHITE), ('blue', BLUE)]:
    (BRAND / 'logos' / f'rightrefer-{name}.svg').write_text(svg(lockup(color), WIDTH, 64))
    (BRAND / 'logos' / f'rightrefer-mono-{name}.svg').write_text(svg(lockup(color, True), WIDTH, 64))
    (BRAND / 'symbols' / f'rightrefer-mark-{name}.svg').write_text(svg(mark(color), 96, 96))
(BRAND / 'symbols/rightrefer-mark-color.svg').write_text(svg(mark(), 96, 96))
(BRAND / 'icons/rightrefer-app-icon.svg').write_text(svg(app_icon(), 96, 96))
(PUBLIC / 'rightrefer-logo.svg').write_text(svg(mark(), 96, 96))
(PUBLIC / 'favicon.svg').write_text(svg(app_icon(compact=True), 96, 96))
(BRAND / 'icons/favicon.svg').write_text(svg(app_icon(compact=True), 96, 96))
(ROOT / 'src/lib/brand.ts').write_text('// Generated by scripts/generate-brand.py. Do not edit by hand.\n' +
    f'export const BRAND_MARK_PARTS = {json.dumps(PARTS, indent=2)} as const;\n' +
    f'export const BRAND_WORDMARK_PATH = {json.dumps(WORD)};\n' +
    f'export const BRAND_LOCKUP_WIDTH = {WIDTH};\n')

# Outlined text keeps social cards independent of installed fonts.
headline1, _ = outline('The right referral.', WORDMARK_FONT, 90, 80, 300)
headline2, _ = outline('Your way in.', WORDMARK_FONT, 90, 80, 399)
caption, _ = outline('Professional introductions, handled carefully.', FONT, 22, 82, 535, -.2)
social = f'<rect width="1200" height="630" fill="{PAPER}"/><g transform="translate(69 55) scale(.78)">{lockup()}</g><path fill="{INK}" d="{headline1}"/><path fill="{BLUE}" d="{headline2}"/><path fill="{INK}" d="{caption}"/><g transform="translate(854 173) scale(2.65)">{mark()}</g>'
(PUBLIC / 'og-image.svg').write_text(svg(social, 1200, 630, 'RightRefer. The right referral. Your way in.'))
(BRAND / 'social/og-image.svg').write_text(svg(social, 1200, 630, 'RightRefer. The right referral. Your way in.'))


def label(text, x, y, color=INK, size=16):
    path, _ = outline(text, FONT, size, x, y)
    return f'<path fill="{color}" d="{path}"/>'


# Restrained presentation: actual assets, not a speculative product mockup.
board = f'<rect width="1440" height="960" fill="{PAPER}"/>'
board += label('RIGHTREFER   /   FORWARD', 64, 60, size=14)
board += label('Identity study — September 2026', 1100, 60, size=12)
board += f'<g transform="translate({(1440-WIDTH*3)/2:.3f} 175) scale(3)">{lockup()}</g>'
board += label('The right people. New possibilities.', 484, 417, size=24)
board += f'<rect y="494" width="940" height="466" fill="{INK}"/>'
board += label('COLOUR, WITH RESTRAINT.', 64, 544, WHITE, 13)
board += f'<g transform="translate(58 613) scale(1.95)">{lockup(WHITE)}</g>'
for x, size in [(64, 16), (146, 24), (234, 32), (330, 48)]:
    board += f'<g transform="translate({x} {839-size}) scale({size/96})">{mark(WHITE)}</g>'
    board += label(f'{size} px', x, 871, WHITE, 12)
board += label('THE APP ICON', 992, 544, size=13)
board += f'<g transform="translate(1090 601) scale(2.4)">{app_icon()}</g>'
board += label('Recognizable at a glance.', 1070, 881, size=16)
(ROOT / 'docs/brand/rightrefer-identity.svg').write_text(svg(board, 1440, 960, 'RightRefer Forward identity, colour wordmark, dark usage, monochrome sizes, and app icon'))
proof = f'<rect width="600" height="280" fill="{PAPER}"/><rect y="140" width="600" height="140" fill="{INK}"/>'
for y, color in [(42, INK), (182, WHITE)]:
    for x, width in [(40, 144), (280, 240)]:
        proof += f'<g transform="translate({x} {y}) scale({width/WIDTH})">{lockup(color)}</g>'
        proof += label(f'{width} px', x, y+65, color, 12)
(ROOT / 'docs/brand/louize-size-proof.svg').write_text(svg(proof, 600, 280, 'Louize RightRefer wordmark at 144 and 240 pixels in light and dark'))
print(f'Generated Forward brand assets. Lockup viewBox: 0 0 {WIDTH} 64')
